model:
  # selection-only config (no kwargs/hyperparams)
  text_encoder: "text_encoder_smalvlm.model"
  vlm_encoder: "vlm_encoder_clip.model"
  connecter: "connecter_type1.model"

training:
  batch_size: 8
  num_epochs: 3
  learning_rate: 5e-5
  weight_decay: 0.01
  warmup_steps: 1000
  logging_steps: 100
  save_steps: 500
  gpu : [1,2]
  debug: False

dataset:
  name: "wikitext-2"
  split: "train"
  max_length: 512
  num_workers: 4  

output:
  save_dir: "./model1" ## checkpoints,logs and data will be saved here
  print_output: true
  load_latest_checkpoint: False ##add this - if latest checkpoint exists in save_dir, 
  ##it will be loaded and training will resume from there. If False, training will start from scratch.
